/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Song = IDL.Record({
  'id' : IDL.Text,
  'albumArt' : IDL.Text,
  'title' : IDL.Text,
  'album' : IDL.Text,
  'previewUrl' : IDL.Text,
  'artist' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MusicPreferences = IDL.Record({
  'languages' : IDL.Vec(IDL.Text),
  'artists' : IDL.Vec(IDL.Text),
  'genres' : IDL.Vec(IDL.Text),
});
export const PlayEvent = IDL.Record({
  'title' : IDL.Text,
  'songId' : IDL.Text,
  'skipped' : IDL.Bool,
  'playedAt' : IDL.Int,
  'liked' : IDL.Bool,
  'artist' : IDL.Text,
});
export const PlaylistDTO = IDL.Record({ 'name' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSongToPlaylist' : IDL.Func([IDL.Text, Song], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [], []),
  'deletePlaylist' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMusicPreferences' : IDL.Func([], [IDL.Opt(MusicPreferences)], ['query']),
  'getPlayHistory' : IDL.Func([], [IDL.Vec(PlayEvent)], ['query']),
  'getSongsInPlaylist' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'getUserLikedSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getUserPlaylists' : IDL.Func([], [IDL.Vec(PlaylistDTO)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeSong' : IDL.Func([Song], [], []),
  'recordPlayEvent' : IDL.Func([PlayEvent], [], []),
  'removeSongFromPlaylist' : IDL.Func([IDL.Text, Song], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMusicPreferences' : IDL.Func([MusicPreferences], [], []),
  'searchMusic' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlikeSong' : IDL.Func([Song], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Song = IDL.Record({
    'id' : IDL.Text,
    'albumArt' : IDL.Text,
    'title' : IDL.Text,
    'album' : IDL.Text,
    'previewUrl' : IDL.Text,
    'artist' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MusicPreferences = IDL.Record({
    'languages' : IDL.Vec(IDL.Text),
    'artists' : IDL.Vec(IDL.Text),
    'genres' : IDL.Vec(IDL.Text),
  });
  const PlayEvent = IDL.Record({
    'title' : IDL.Text,
    'songId' : IDL.Text,
    'skipped' : IDL.Bool,
    'playedAt' : IDL.Int,
    'liked' : IDL.Bool,
    'artist' : IDL.Text,
  });
  const PlaylistDTO = IDL.Record({ 'name' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSongToPlaylist' : IDL.Func([IDL.Text, Song], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [], []),
    'deletePlaylist' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMusicPreferences' : IDL.Func(
        [],
        [IDL.Opt(MusicPreferences)],
        ['query'],
      ),
    'getPlayHistory' : IDL.Func([], [IDL.Vec(PlayEvent)], ['query']),
    'getSongsInPlaylist' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'getUserLikedSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getUserPlaylists' : IDL.Func([], [IDL.Vec(PlaylistDTO)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeSong' : IDL.Func([Song], [], []),
    'recordPlayEvent' : IDL.Func([PlayEvent], [], []),
    'removeSongFromPlaylist' : IDL.Func([IDL.Text, Song], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMusicPreferences' : IDL.Func([MusicPreferences], [], []),
    'searchMusic' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlikeSong' : IDL.Func([Song], [], []),
  });
};

export const init = ({ IDL }) => { return []; };